scheme: Gemini

favicon:
  small: /icons/avatar_16x16.png
  medium: /icons/avatar_32x32.png
  apple_touch_icon: /icons/apple-touch-icon-next.png
  safari_pinned_tab: /icons/avatar_256x256.png

creative_commons:
  # Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
  license: by-nc-sa
  size: big
  sidebar: true
  post: false


menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  about: /about/ || fa fa-user
  友情链接: /friends/ || fa fa-heart
  sitemap: /sitemap.txt || fa fa-sitemap

menu_settings:
  icons: true
  badges: true

sidebar:
  display: always

avatar:
  url: /icons/avatar_256x256.png
  rounded: true
  rotated: true

social:
  GitHub: https://github.com/keunlas || fab fa-github

social_icons:
  enable: true
  icons_only: true
  transition: true

footer:
  since: 2025
  icon:
    animated: true
  copyright: Keunlas
  powered: false

post_meta:
  updated_at:
    enable: false

symbols_count_time:
  item_text_total: true

tag_icon: true

codeblock:
  copy_button:
    enable: true
    style: mac
  language: true










